MasterAnnonceLogin {
    org.univ_paris8.iut.montreuil.qdev.tp2025.ponnou.tp1.tp1.auth.jaas.DbLoginModule required;
};

MasterAnnonceToken {
    org.univ_paris8.iut.montreuil.qdev.tp2025.ponnou.tp1.tp1.auth.jaas.TokenLoginModule required;
};
